// <auto-generated />
using System;
using CRUSDL;
using CRUSModels;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CRUSDL.Migrations
{
    

    [DbContext(typeof(ClothesRUSdemoContext))]
    partial class ClothesRUSdemoContextModelSnapshot : ModelSnapshot
    {
        
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:Collation", "SQL_Latin1_General_CP1_CI_AS")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CRUSModels.Customer", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int")
                        .HasColumnName("Customer_ID");

                    b.Property<string>("Email")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("ID");

                    b.ToTable("Customer");
                });

            modelBuilder.Entity("CRUSModels.LineItem", b =>
                {
                    b.Property<int>("LineItemId")
                        .HasColumnType("int")
                        .HasColumnName("LineItem_ID");

                    b.Property<int>("OrderId")
                        .HasColumnType("int")
                        .HasColumnName("Order_ID");

                    b.Property<string>("OrderPlacement")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("OrderPlacementOrderId")
                        .HasColumnType("int");

                    b.Property<string>("Product")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int")
                        .HasColumnName("Product_ID");

                    b.Property<int>("_quantity")
                        .HasColumnType("int");

                    b.HasKey("LineItemId");

                    b.HasIndex("OrderPlacementOrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("LineItem");
                });

            modelBuilder.Entity("CRUSModels.OrderPlacement", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("order_ID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CustomerId")
                        .HasColumnType("int")
                        .HasColumnName("Customer_ID");

                    b.Property<int>("ProductId")
                        .HasColumnType("int")
                        .HasColumnName("Product_ID");

                    b.Property<int>("StoreFrontId")
                        .HasColumnType("int")
                        .HasColumnName("StoreFront_ID");

                    b.Property<int>("TotalPrice")
                        .HasColumnType("int")
                        .HasColumnName("Total_Price");

                    b.Property<int?>("orderPlacementOrderId")
                        .HasColumnType("int");

                    b.HasKey("OrderId")
                        .HasName("PK__OrderPla__464665E1B7D4693B");

                    b.HasIndex("CustomerId")
                        .IsUnique();

                    b.HasIndex("ProductId");

                    b.HasIndex("StoreFrontId");

                    b.HasIndex("orderPlacementOrderId");

                    b.ToTable("OrderPlacement");
                });

            modelBuilder.Entity("CRUSModels.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Product_ID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("LineItemId")
                        .HasColumnType("int")
                        .HasColumnName("LineItem_ID");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<int>("StoreFrontId")
                        .HasColumnType("int")
                        .HasColumnName("StoreFront_ID");

                    b.HasKey("ProductId");

                    b.HasIndex("StoreFrontId");

                    b.ToTable("Product");
                });

            modelBuilder.Entity("CRUSModels.StoreFront", b =>
                {
                    b.Property<int>("StoreFrontId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("StoreFront_ID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("ListOfOrders")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("List_of_Orders");

                    b.Property<string>("ListOfProducts")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("List_of_Products");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("StoreFrontId");

                    b.ToTable("StoreFront");
                });

            modelBuilder.Entity("CRUSModels.LineItem", b =>
                {
                    b.HasOne("CRUSModels.OrderPlacement", null)
                        .WithMany("LineItems")
                        .HasForeignKey("OrderPlacementOrderId");

                    b.HasOne("CRUSModels.Product", null)
                        .WithMany("LineItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CRUSModels.OrderPlacement", b =>
                {
                    b.HasOne("CRUSModels.Customer", "Customer")
                        .WithOne("orderPlacements")
                        .HasForeignKey("CRUSModels.OrderPlacement", "CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CRUSModels.Product", "product")
                        .WithMany("OrderPlacements")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CRUSModels.StoreFront", "StoreFront")
                        .WithMany("_orderPlacement")
                        .HasForeignKey("StoreFrontId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CRUSModels.OrderPlacement", "orderPlacement")
                        .WithMany()
                        .HasForeignKey("orderPlacementOrderId");

                    b.Navigation("Customer");

                    b.Navigation("orderPlacement");

                    b.Navigation("product");

                    b.Navigation("StoreFront");
                });

            modelBuilder.Entity("CRUSModels.Product", b =>
                {
                    b.HasOne("CRUSModels.StoreFront", "StoreFront")
                        .WithMany("Products")
                        .HasForeignKey("StoreFrontId")
                        .HasConstraintName("FK__Product__StoreFr__114A936A")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StoreFront");
                });

            modelBuilder.Entity("CRUSModels.Customer", b =>
                {
                    b.Navigation("orderPlacements");
                });

            modelBuilder.Entity("CRUSModels.OrderPlacement", b =>
                {
                    b.Navigation("LineItems");
                });

            modelBuilder.Entity("CRUSModels.Product", b =>
                {
                    b.Navigation("LineItems");

                    b.Navigation("OrderPlacements");
                });

            modelBuilder.Entity("CRUSModels.StoreFront", b =>
                {
                    b.Navigation("_orderPlacement");

                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
